# Generated by Django 3.1.4 on 2021-01-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('genero', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='femenino', max_length=30)),
                ('estadoCivil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('union', 'Unión Libre'), ('divorciado', 'Divoraciado'), ('viudo', 'Viudo'), ('separado', 'Separado')], default='soltero', max_length=30)),
                ('correo', models.EmailField(max_length=105)),
                ('telefono', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('direccion', models.TextField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fechaApertura', models.DateTimeField(auto_now_add=True)),
                ('tipoCuenta', models.CharField(choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente'), ('programado', 'Programado')], default='ahorros', max_length=30)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('trasaccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('deposito', 'Depósito'), ('retiro', 'Retiro')], default='deposito', max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(default='Descripción de la transacción')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_ad', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.cuenta')),
            ],
        ),
    ]
